# Use official python base image
FROM python:3.11

# Set working directory in container
WORKDIR /app

# Copy files to container
COPY Hello.py .

# Run the script when container starts 
CMD ["python","Hello.py"]